const movieListTypes = {
  FETCH_MOVIES_REQUEST: " FETCH_MOVIES_REQUEST",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_ERROR: "FETCH_MOVIES_ERROR",
  SORT_MOVIES: "SORT_MOVIES",
  DELETE_MOVIE: "DELETE_MOVIE",
};

export default movieListTypes;
